---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: otus-msa-hw6
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: order-service
